version: 2

python:
   version: "3.6"
   install:
      - requirements: docs/requirements-rtd.txt
      # no - method: pip here, -e . is already in docs/requirements-rtd.txt

   system_packages: true
